echo From %1
copy %1\installed\x64-windows\debug\bin\avcodec-60.dll ..\x64\debug
copy %1\installed\x64-windows\debug\bin\avcodec-60.pdb ..\x64\debug
copy %1\installed\x64-windows\debug\bin\avformat-60.dll ..\x64\debug
copy %1\installed\x64-windows\debug\bin\avformat-60.pdb ..\x64\debug
copy %1\installed\x64-windows\debug\bin\avutil-58.dll ..\x64\debug
copy %1\installed\x64-windows\debug\bin\avutil-58.pdb ..\x64\debug
copy %1\installed\x64-windows\debug\bin\brotlicommon.dll ..\x64\debug
copy %1\installed\x64-windows\debug\bin\brotlicommon.pdb ..\x64\debug
copy %1\installed\x64-windows\debug\bin\brotlidec.dll ..\x64\debug
copy %1\installed\x64-windows\debug\bin\brotlidec.pdb ..\x64\debug
copy %1\installed\x64-windows\debug\bin\double-conversion.dll ..\x64\debug
copy %1\installed\x64-windows\debug\bin\double-conversion.pdb ..\x64\debug
copy %1\installed\x64-windows\debug\bin\Halide.dll ..\x64\debug
copy %1\installed\x64-windows\debug\bin\Halide.pdb ..\x64\debug
copy %1\installed\x64-windows\debug\bin\harfbuzz.dll ..\x64\debug
copy %1\installed\x64-windows\debug\bin\harfbuzz.pdb ..\x64\debug
copy %1\installed\x64-windows\debug\bin\jpeg62.dll ..\x64\debug
copy %1\installed\x64-windows\debug\bin\jpeg62.pdb ..\x64\debug
copy %1\installed\x64-windows\debug\bin\liblzma.dll ..\x64\debug
copy %1\installed\x64-windows\debug\bin\liblzma.pdb ..\x64\debug
copy %1\installed\x64-windows\debug\bin\libsharpyuv.dll ..\x64\debug
copy %1\installed\x64-windows\debug\bin\libsharpyuv.pdb ..\x64\debug
copy %1\installed\x64-windows\debug\bin\libwebp.dll ..\x64\debug
copy %1\installed\x64-windows\debug\bin\libwebp.pdb ..\x64\debug
copy %1\installed\x64-windows\debug\bin\libwebpdecoder.dll ..\x64\debug
copy %1\installed\x64-windows\debug\bin\libwebpdecoder.pdb ..\x64\debug
copy %1\installed\x64-windows\debug\bin\libwebpmux.dll ..\x64\debug
copy %1\installed\x64-windows\debug\bin\libwebpmux.pdb ..\x64\debug
copy %1\installed\x64-windows\debug\bin\openjp2.dll ..\x64\debug
copy %1\installed\x64-windows\debug\bin\openjp2.pdb ..\x64\debug
copy %1\installed\x64-windows\debug\bin\swresample-4.dll ..\x64\debug
copy %1\installed\x64-windows\debug\bin\swresample-4.pdb ..\x64\debug
copy %1\installed\x64-windows\debug\bin\zstd.dll ..\x64\debug
copy %1\installed\x64-windows\debug\bin\zstd.pdb ..\x64\debug
